services:
  controle-semanal:
    build: .
    container_name: controle-semanal
    ports:
      - "8080:8080"
    volumes:
      - controle-semanal-data:/app2/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 650M
          
volumes:
  controle-semanal-data: