spring.application.name=controle-semanal

# ========================================
# POSTGRESQL
# ========================================
spring.datasource.url=jdbc:postgresql://pg.gomesdev87.tech:5432/finace
spring.datasource.username=gomes
spring.datasource.password=gomes123
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================================
# JPA / HIBERNATE
# ========================================
# ❌ ERRADO: org.hibernate.community.dialect.PostgreSQLDialect
# ✅ CERTO:
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Pool de conexões leve
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2